# Generated by Django 2.1.8 on 2019-06-29 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('price', models.IntegerField()),
                ('lastpay', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.TextField(max_length='50')),
            ],
        ),
        migrations.AddField(
            model_name='custom',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsmanager.Sub'),
        ),
        migrations.AddField(
            model_name='custom',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
