# Generated by Django 2.1.8 on 2019-06-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='lastpay',
            field=models.DateField(),
        ),
    ]
